### ISSUE TITLE
Can't install: tensorflow-gpu library not found?

### ISSUE THREAD

**Issue by Mr-Mondragon** [bhansconnect/alpha_zero_othello#2]
As per the given instructions I'm running `pip install -r requirements.txt` but after installing a bunch of stuff I'm getting this fatal error:

> Collecting tensorflow-gpu==1.4.0 (from -r requirements.txt (line 21))
>   Could not find a version that satisfies the requirement tensorflow-gpu==1.4.0 (from -r requirements.txt (line 21)) (from versions: 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0)
> No matching distribution found for tensorflow-gpu==1.4.0 (from -r requirements.txt (line 21))

Unfortunately I have zero experience with tensorflow (or pip, for that matter). Is there an easy way to work around this?

**Comment by Mr-Mondragon** [comment]
Operating system: macOS High Sierra (10.13.4)
Running `python --version` says: Python 2.7.15.
Running `python3 --version` says: Python 3.7.0.

**Comment by bhansconnect** [comment]
When trying to run my code, does it work if you use pip3 and python3 instead of pip and python?

**Comment by Mr-Mondragon** [comment]
I tried `pip3 install -r requirements.txt`, at first I got an error about some library being outdated and having to run `pip install --upgrade pip`.
I assumed I had to run `pip3 install --upgrade pip` instead, which seemed to get rid of the first error.

When running `pip3 install -r requirements.txt` again I now got a rather long error log, which I [uploaded here](https://pastebin.com/raw/3U38ZCHR) in case it explains anything, I hope this is of any help?

**Comment by bhansconnect** [comment]
So I was looking into `tensorflow 1.4.0` on mac and apparently as of `tensorflow 1.2.0`, gpu is not supported on mac. That makes things interesting.

That leaves a few possible options:
1. Try using just` tensorflow` instead of `tensorflow-gpu` in `requirements.txt`. This will greatly lower speed but should be functional, especially if you just want to play the best model.
2. Try using `tensorflow-gpu` version`1.1.0`. I have no idea if this will function correctly, but it may be worth trying. 
3. Try using a different computer that isn't mac.

**Comment by Mr-Mondragon** [comment]
Thanks for the suggestions and feedback, much appreciated. Unfortunately with 1 and 2 I'm still getting the same long list of error output, and 3 is not an option (I only have a mac). 

Note however that I see a lot of compile errors that seem to be related to numpy. Now that I think of it, that was also the module that caused the initial error, warning me to upgrade pip3. In particular I see a bunch of errors related to numpy/random/mtrand/mtrand.c which I assume is a mersenne prime twister based random generator (I know because that's what it's also called in php). Either way some part of the numpy library, not related to tensorflow. 

If I just do this: `pip3 install numpy==1.14.0` I am also getting that same bunch of errors.

Could there be something else wrong or missing, or is there anything else I can check or update about my code environment, which may help resolve the errors from building/installing numpy?

**Comment by bhansconnect** [comment]
You might want to try installing libraries one by one and not restricting the versions. I would start with trying to get Tensorflow and Keras to work because they are the most important. I think it might be possible that some of the versions I have specified do not work well with mac. 

I wish I had more knowledge about your issue, but it is an issue with the C in numpy compiling on your mac.

**Comment by bhansconnect** [comment]
Potentially you could try using [Anaconda](https://www.anaconda.com/download/#macos) with my environment.yml file(or manual install in conda) to see if that will allow you to properly install the libraries.
